/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ece651.sp22.nd157.battleship;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintStream;
import java.io.Reader;

public class App {
  private TextPlayer player1;
  private TextPlayer player2;

  public App(TextPlayer p1, TextPlayer p2) {
    this.player1 = p1;
    this.player2 = p2;
  }

  public static void main(String[] args) throws IOException {
    /**
     * The execution file for the game, it creates a board, initialize two players
     * and ask them where to place the ship
     *
     * @params args is the argument that can be used to manipulate the program
     */
    Board<Character> b1 = new BattleShipBoard<Character>(10, 20,'X');
    Board<Character> b2 = new BattleShipBoard<Character>(10, 20,'X');
    BufferedReader input = new BufferedReader(new InputStreamReader(System.in));
    V1ShipFactory factory = new V1ShipFactory();
    TextPlayer p1 = new TextPlayer("A", b1, input, System.out, factory);
    TextPlayer p2 = new TextPlayer("B", b2, input, System.out, factory);
    App app = new App(p1, p2);
    app.doPlacementPhase();
  }

  public void doPlacementPhase() throws IOException {
    /**
     * use the textplayer's method to prompt both users to place a ship
     */
    player1.doPlacementPhase();
    player2.doPlacementPhase();
  }
}
